[project]
name = "newgridcon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Krzysztof Olszewski", email = "Krzysztof Olszewski" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
newgridcon = "newgridcon:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
